---
title: "Monitoring Effects and Monitoring Rates 2013 - 2021"
output: html_document
date: "`r Sys.Date()`"
editor_options: 
  chunk_output_type: console
---

```{r start, echo = FALSE, message = FALSE, warning = FALSE}
# Set random number seed ----
set.seed(49)

# Get packages ----
library(data.table)
library(flextable)
library(ROracle)
library(scales)
library(tidyverse)

# Get custom permutation test function ----
source("analyses/monitoring_effects/perm_test.R")

# Get data ----
if(file.exists("source_data/valhalla_2013_2021.RData")){
load("source_data/valhalla_2013_2021.RData")
  
} else {
  
# Establish database connection
channel <- eval(parse(text = Sys.getenv("channel_afsc")))

# Pull data from database
val <- setDT(dbGetQuery(channel, "select * from loki.akr_valhalla where adp < 2022"))

# Save data
save(val, file = "source_data/valhalla_2013_2021.RData")
}

# Don't print code ----
knitr::opts_chunk$set(echo = FALSE)
```

```{r wrangle, include = FALSE}
# Select rows of interest ----
perm_data <- val[COVERAGE_TYPE != "FULL" & !(STRATA %in% c("FULL", "ZERO", "ZERO_EM_RESEARCH", "EM", "EM Voluntary"))]

# Conform strata to those used in most recent ADP ----

# Split trips from 2013 and 2014 that fished both POT and TRW gear
perm_data[TRIP_ID %in% perm_data[STRATA == "TRIP" & AGENCY_GEAR_CODE == "POT", TRIP_ID] & TRIP_ID %in% perm_data[STRATA == "TRIP" & AGENCY_GEAR_CODE == "TRW", TRIP_ID], TRIP_ID := ifelse(AGENCY_GEAR_CODE == "POT", paste0(TRIP_ID, ".1"), paste0(TRIP_ID, ".2"))]

# Relabel 2013 and 2014 strata using gear type
perm_data[STRATA %in% c("TRIP", "VESSEL", "T", "t"), STRATA := AGENCY_GEAR_CODE]

# Recode tender strata
perm_data[, STRATA := as.character(recode(STRATA, "EM_TenP" = "EM_POT", "TenH" = "HAL", "TenP" = "POT", "TenTR" = "TRW"))]

# View combo strata trips
unique(perm_data[, N := uniqueN(STRATA), by = .(TRIP_ID)
          ][N > 1, .(ADP, TRIP_ID, STRATA, AGENCY_GEAR_CODE)])

# For combo strata trips, default to the (non-JIG) stratum with the most landed weight
perm_data[, N := uniqueN(STRATA), by = .(TRIP_ID)
          ][N > 1, STRATA_WEIGHT := sum(WEIGHT_POSTED[SOURCE_TABLE == "Y" & STRATA != "JIG"]), by = .(TRIP_ID, STRATA)
            ][N > 1, ':=' (COVERAGE_TYPE = COVERAGE_TYPE[which.max(STRATA_WEIGHT)], STRATA = STRATA[which.max(STRATA_WEIGHT)]), by = .(TRIP_ID)
              ][, ':=' (N = NULL, STRATA_WEIGHT = NULL)]

# Calculate permutation test metrics ----

# Number of areas fished
perm_data[, N_AREAS := as.numeric(length(unique(REPORTING_AREA_CODE))), by=.(TRIP_ID, STRATA)]

# Trip duration in days (removes 6 trips that had landing date before trip start)
perm_data <- perm_data[, MIN_DATE := min(as.Date(TRIP_TARGET_DATE)), by = .(TRIP_ID, STRATA)
                       ][, MAX_DATE := max(as.Date(LANDING_DATE)), by = .(TRIP_ID, STRATA)
                         ][, DAYS := as.numeric(difftime(MAX_DATE, MIN_DATE, units = "days") + 1), by = .(TRIP_ID, STRATA)
                           ][, c("TRIP_TARGET_DATE", "LANDING_DATE", "MIN_DATE", "MAX_DATE") := NULL
                             ][DAYS > 0]
# Length overall  
perm_data[, LENGTH_OVERALL := as.numeric(LENGTH_OVERALL)]

# Number of species
perm_data[, N_SPECIES := as.numeric(length(unique(AGENCY_SPECIES_CODE[SOURCE_TABLE == "Y"]))), by = .(TRIP_ID, STRATA)]

# Landed catch
perm_data[, LANDED_CATCH := sum(as.numeric(WEIGHT_POSTED[SOURCE_TABLE == "Y"])), by = .(TRIP_ID, STRATA)]

# Proportion of catch that is predominant species (pMax)
perm_data[, SPECIES_WEIGHT := sum(WEIGHT_POSTED[SOURCE_TABLE == "Y"], na.rm = TRUE), by = .(TRIP_ID, STRATA, AGENCY_SPECIES_CODE)
          ][, PMAX := max(SPECIES_WEIGHT/LANDED_CATCH), by = .(TRIP_ID, STRATA)
            ][, SPECIES_WEIGHT := NULL]

# Isolate columns of interest and make rows unique
perm_data <- unique(perm_data[, .(ADP, VESSEL_ID, TRIP_ID, COVERAGE_TYPE, STRATA, TENDER, OBSERVED_FLAG, N_AREAS, DAYS, LENGTH_OVERALL, N_SPECIES, PMAX, LANDED_CATCH)])
```

```{r perm_test}
units        <- "TRIP_ID"
metrics      <- c("N_AREAS", "DAYS", "LENGTH_OVERALL", "N_SPECIES", "PMAX", "LANDED_CATCH")
groups       <- c("ADP", "STRATA")
yn_var       <- "OBSERVED_FLAG"
n_rep        <- 1000
boxcox       <- FALSE

if(file.exists("results/perm_results.RData")){
  load("results/perm_results.RData")
  
} else {

perm_results <- perm_test(data = perm_data, units, metrics, groups, yn_var, n_rep, boxcox)
save(perm_results, file = "results/perm_results.RData")
}
```

```{r figure_1}
# Get percent differences and monitoring rates from the permutation test results
dat   <- perm_results$N_table[perm_results$obs[SCALE == "PCT"], on = .(ADP, STRATA)]
dat   <- melt(dat, id.vars = c(groups, "N", "n", "rate"), measure.vars = metrics, variable.name = "metric", value.name = "pct_diff")
dat[, abs_pct_diff := abs(pct_diff)]
p_val <- melt(perm_results$`p-value`, id.vars = groups, measure.vars = metrics, variable.name = "metric", value.name = "p_val")
dat   <- dat[p_val, on = .(ADP, STRATA, metric)][, sig_point := ifelse(p_val < 0.05/length(metrics), "Yes", "No")]

# Construct a linear model of percent difference ~ rate for each stratum and metric combination
mod <- lm(abs_pct_diff ~ -1 + STRATA:metric + n:STRATA:metric, data = dat)

# Extract the slope coefficients from the linear model
mod_df <- data.frame(name = names(mod$coefficients), slope = unname(mod$coefficients), p_val = unname(summary(mod)[["coefficients"]][, "Pr(>|t|)"]))
mod_df <- mod_df %>%
filter(grepl("n", name)) %>%
mutate(STRATA = str_match(name, "STRATA\\s*(.*?)\\s*:metric")[,2],
       metric = str_match(name, "metric\\s*(.*?)\\s*:n")[,2],
       sig_slope = ifelse(p_val < 0.05/length(metrics), "Yes", "No")) %>%
select(STRATA, metric, slope, sig_slope)

# Join the slope coefficients back onto the permutation test results
dat <- dat[setDT(mod_df), on = .(STRATA, metric)]

# Recode strata and metrics for the figure
dat[, ':=' (STRATA = str_replace_all(STRATA, "_", " "), 
            metric = as.character(recode(metric, 
                     "N_AREAS" = "NMFS areas", 
                     "DAYS" = "Days fished", 
                     "LENGTH_OVERALL" = "Vessel length (ft)", 
                     "N_SPECIES" = "Species landed", 
                     "PMAX" = "pMax", 
                     "LANDED_CATCH" = "Landed catch (t)")))]

# Create figure
f1 <- ggplot(dat[STRATA != "EM TRW EFP"], aes(x = n, y = abs_pct_diff)) +
      stat_smooth(aes(color = sig_slope), method = "lm", formula = 'y ~ x', se = FALSE) +
      geom_point(aes(color = sig_point)) +
      geom_hline(yintercept = 0, lty = 3) +
      facet_grid(metric ~ STRATA, scales = "free") +
      scale_color_manual(values = c("Yes" = "red", "No" = "black")) +
      labs(x = "Sample size", y = "Absolute % difference in means (monitored - unmonitored)", color = expression(paste(italic("p"), "-value < 0.05/6?", sep = ""))) +
      theme(legend.position = "bottom")

# Print figure
f1

# Save figure
if(!file.exists("output_figures/permutation_pct_diff.png")){
ggsave(filename = "output_figures/permutation_pct_diff.png", width = 11, height = 8.5, units = 'in')
}
```
  
Figure 1. The absolute percent differences in means (monitored - unmonitored) against sample size for years 2013 through 2021. Each point represents one year of data. Lines represent the linear regression of the points.