# Preliminary Rates for 2024 Draft ADP (PCFMAC and FMSC)

#======================================================================================================================#
# Preparation ----------------------------------------------------------------------------------------------------------
#======================================================================================================================#

#===================#
## Load Packages ----
#===================#

library(data.table)         # Data wrangling
library(ggplot2)            # Plotting
library(grid)               # For unit.pmax  to get widths of grobs so that plots have matching dimensions
library(gridExtra)          # For arrangeGrob to combine plots
library(sf)                 # Spatial analyses
library(flextable)          # For print-ready tables
library(dplyr)              # For piping and handling sf objects

#=============================#
## Load data and data prep ----
#=============================#

# Fishing effort data from 2018 to 2022
# `spatiotemporal_boxes.rdata' is generated by /analyses/spatiotemporal_boxes/data_prep.R
load("analyses/allocation_evaluation/allocation_evaluation.Rdata")   # loads pc_effort_dt and trips_melt
val_2018_2022_dt <- pc_effort_dt[ADP %in% 2018:2022]

# Load the ADFG statistical area shapefile. '../' is needed for Rmarkdown to climb into parent folders.
stat_area_sf <- st_read(
  dsn = "source_data/ADFG_Stat_Area_shapefile/PVG_Statewide_2001_Present_GCS_WGS1984.shp", quiet = T) %>%
  select(STAT_AREA) %>%
  st_transform(crs = 3467)

# Load the Alaska map sf objects
load("source_data/ak_shp.rdata")      # shp_land, shp_nmfs, and shp_centroids added to global

#===============================#
## Prepare trips_melt object ----
#===============================#

# trips_melt has metrics and trip duration for all trips >= 2015. . 
# Add ADP year, STRATA, and DAYS of each TRIP_ID to trips_melt
trips_melt_add_data <- unique(pc_effort_dt[STRATA != "ZERO", .(ADP, TRIP_ID, STRATA, DAYS)])
trips_melt <- trips_melt_add_data[trips_melt, on = .(TRIP_ID)]
setcolorder(trips_melt, c("ADP", "STRATA", "TRIP_ID", "DAYS", "Metric", "Value"))
setkey(trips_melt, ADP, STRATA, TRIP_ID, DAYS, Metric, Value)
# Error-check
if(nrow(trips_melt[, .N, by = .(TRIP_ID)][N != uniqueN(trips_melt$Metric)])) stop("At least one trip has number of metrics != 3!")
# Remove records missing data
trips_melt <- trips_melt[!is.na(ADP)]

#===============#
## Functions ----
#===============#

source("analyses/allocation_evaluation/functions.R")

#=======================#
## Monitoring  Costs ----
#=======================#

# Derived from: https://docs.google.com/spreadsheets/d/1kcdLjq2Ck4XJBYP0EhrQpuknRgtQFt01LN3xUaCg7cI/edit?usp=sharing
# Monitoring cost models are applyed by ob_cost(), emfg_cost(), and emtrw_cost() functions
# Set all parameters involving monitoring costs
cost_params <- list(
  
  OB = list(
    day_rate_intercept          = 1870.4466666667,    # To calculate the sea day cost
    day_rate_slope              =   -0.2263733333,    # To calculate the sea day cost
    travel_day_rate             =  423.7867560407     # Expected cost of travel per day
  ),
  
  EMFG = list(
    emfg_v                      =  172,               # Size of fixed-gear EM vessel pool
    cost_per_vessel             = 5679.9002264045,
    cost_per_review_day         =  150.3237858616
  ),
  
  EMTRW = list(
    emtrw_goa_v                 =   25,               # TODO Number of EM_TRW vessels that fish exclusively in the GOA. 39 for 2024, 25 for 2022 (using 22 from 2021, 3 added in 2022, all of those vessels in the GOA-only list in 2024)
    trip_to_plant_factor        =    3.8059361492,    # Used to predict plant days from trips
    amortized_equipment_per_VY  = 4100.7124800000,    # Per (Vessel x Year) amortized EM equipment install costs for GOA-only vessels
    equipment_upkeep_per_VY     = 4746.0398955882,    # Per (Vessel x Year) EM equipment maintenance cost for GOA-only vessels
    review_day_rate             =   27.9918948996,    # Per sea day cost for EM compliance review
    plant_day_rate              =  908.2225000000     # Per plant day cost for shoreside monitoring by observers
  )
)

#======================#
## Other Parameters ----
#======================#

sample_rate_vec <- seq(from = 0.0001, to = 0.9950, by = 0.0001) 
max_budget <- 7e6    # This is used as a cutoff for allocation functions.


#======================================================================================================================#
# Designs --------------------------------------------------------------------------------------------------------------
#======================================================================================================================#

#=============================#
## Stratification: Current ----
#=============================#

# Current box definitions
system.time(current.box <- define_boxes(
  val_2018_2022_dt, c(2e5, 2e5), time = c("week", 1, "TRIP_TARGET_DATE", "LANDING_DATE"),
  year_col = "ADP", stratum_cols = "STRATA", dmn_cols = c("BSAI_GOA", "GEAR"), geom = T))

# Apply current stratum definition and calculate mean trip durations
current.allo_lst <- update_strata(pc_effort_dt, trips_melt, stratum_cols = c("STRATA"), focus_years = 2018:2022)

# Estimate monitoring costs from method-specific cost models for a wide range of sample rates. This table will be used
# by all designs as it is design-agnostic. Takes 2-3 minutes to run.
system.time(cost_dt <- rates_to_costs_all(current.allo_lst, sample_rate_vec, cost_params, max_budget))
# FIXME : the ob_cost() model should be changed to logistic so that CPD doesn't decline infinitely with volume of days.
# For now, just exclude any instances where the OB_TOTAL decreases 
cost_dt <- rbindlist(lapply(split(cost_dt, by = "ADP"), function(x) x[(which(x[-.N, OB_TOTAL] < x[-1, OB_TOTAL]))]))

#============================#
### Current x Equal Rates ####

current.equal <- allo_equal2(cost_dt, budget = 4.50e6, current.allo_lst, cost_params)  #  9.25% in 2022
current.equal[ADP == 2022]

#===========================#
### Current x Status Quo ####

current.status_quo <- allo_status_quo(current.allo_lst, budget = 4.5e6, cost_dt, cost_params) # 6.76% is all $4.5M affords
current.status_quo[ADP == 2022]

#====================#
### Current x CWB ####

current.cwb_prop <- calculate_cwb_Ph(current.box, sample_rate_vec)             # no changes needed here
current.cwb_rates <- allo_cwb_loop2(current.cwb_prop, current.allo_lst, cost_params, budget = 4.5e6)
current.cwb_rates2 <- allo_cwb_loop2(current.cwb_prop, current.allo_lst, cost_params, budget = 4.5e6, sqrt_cost = F)  # without sqrt cost weighting
current.cwb_rates$rates[ADP == 2022]
current.cwb_rates2$rates[ADP == 2022]

#=====================#
### Current x PROX ####

current.prox_insp <- calculate_interspersion(current.box, sample_rate_vec, omit_strata = "ZERO")
current.prox_index <- calculate_index2(current.prox_insp, cost_params, current.allo_lst, max_budget)
current.prox_rates <- prox_rates_from_budget2(current.prox_index, budget = 4.5e6)  
current.prox_rates[ADP == 2022]
attr(current.prox_rates, "costs")[ADP == 2022]


#=========================#
## Stratification: FMP ----
#=========================#

# Define boxes, splitting trips into strata based on FMP: BSAI and GOA
system.time(fmp.box <- define_boxes(
  val_2018_2022_dt, c(2e5, 2e5), time = c("week", 1, "TRIP_TARGET_DATE", "LANDING_DATE"),
  year_col = "ADP", stratum_cols = c("STRATA", "BSAI_GOA"), dmn_cols = c("GEAR"), geom = T ))
# Re-calculate trip durations
fmp.allo_lst <- update_strata(pc_effort_dt, trips_melt, stratum_cols = c("STRATA", "BSAI_GOA"), focus_years = 2018:2022)

#========================#
### FMP x Equal Rates ####

fmp.equal <- allo_equal2(cost_dt, budget = 4.50e6, fmp.allo_lst, cost_params)  #  9.25% in 2022
fmp.equal[ADP == 2022]

#=======================#
### FMP x Status Quo ####

fmp.status_quo <- allo_status_quo(fmp.allo_lst, budget = 4.5e6, cost_dt, cost_params) # 6.76% is all $4.5M affords
fmp.status_quo[ADP == 2022]

#================#
### FMP x CWB ####

fmp.cwb_prop <- calculate_cwb_Ph(fmp.box, sample_rate_vec)             # no changes needed here
fmp.cwb_rates <- allo_cwb_loop2(fmp.cwb_prop, fmp.allo_lst, cost_params, budget = 4.5e6)
fmp.cwb_rates2 <- allo_cwb_loop2(fmp.cwb_prop, fmp.allo_lst, cost_params, budget = 4.5e6, sqrt_cost = F)  # without sqrt cost weighting
fmp.cwb_rates$rates[ADP == 2022]
fmp.cwb_rates2$rates[ADP == 2022]

#=================#
### FMP x PROX ####

fmp.prox_insp <- calculate_interspersion(fmp.box, sample_rate_vec, omit_strata = "ZERO")
fmp.prox_index <- calculate_index2(fmp.prox_insp, cost_params, fmp.allo_lst, max_budget)
fmp.prox_rates <- prox_rates_from_budget2(fmp.prox_index, budget = 4.5e6)  
fmp.prox_rates[ADP == 2022]
attr(fmp.prox_rates, "costs")[ADP == 2022]


#=================================#
## Stratification: Fixed x FMP ----
#=================================#

# Redefine fixed-gear strata
fixed.pc_effort <- unique(copy(pc_effort_dt)[STRATA %like% "HAL|POT", STRATA := paste0(POOL, "_", "FIXED")])
fixed.val <- fixed.pc_effort[ADP %in% 2018:2022]
# Define boxes again split by FMP, but make neighboring gear-specific for the fixed-gear strata
system.time(fixed_fmp.box <- define_boxes(
  fixed.val, c(2e5, 2e5), time = c("week", 1, "TRIP_TARGET_DATE", "LANDING_DATE"),
  year_col = "ADP", stratum_cols = c("STRATA", "BSAI_GOA"), dmn_cols = c("GEAR"), geom = T ))
fixed_fmp.allo_lst <- update_strata(fixed.pc_effort, trips_melt, stratum_cols = c("STRATA", "BSAI_GOA"), focus_years = 2018:2022)

#==============================#
### FixedxFMP x Equal Rates ####

fixed_fmp.equal <- allo_equal2(cost_dt, budget = 4.50e6, fixed_fmp.allo_lst, cost_params)  #  9.25% in 2022
fixed_fmp.equal[ADP == 2022]

#=============================#
### FixedxFMP x Status Quo ####

fixed_fmp.status_quo <- allo_status_quo(fixed_fmp.allo_lst, budget = 4.5e6, cost_dt, cost_params) # 6.76% is all $4.5M affords
fixed_fmp.status_quo[ADP == 2022]

#======================#
### FixedxFMP x CWB ####

fixed_fmp.cwb_prop <- calculate_cwb_Ph(fixed_fmp.box, sample_rate_vec)             # no changes needed here
fixed_fmp.cwb_rates <- allo_cwb_loop2(fixed_fmp.cwb_prop, fixed_fmp.allo_lst, cost_params, budget = 4.5e6)
fixed_fmp.cwb_rates2 <- allo_cwb_loop2(fixed_fmp.cwb_prop, fixed_fmp.allo_lst, cost_params, budget = 4.5e6, sqrt_cost = F)  # without sqrt cost weighting
fixed_fmp.cwb_rates$rates[ADP == 2022]
fixed_fmp.cwb_rates2$rates[ADP == 2022]

#=======================#
### FixedxFMP x PROX ####

fixed_fmp.prox_insp <- calculate_interspersion(fixed_fmp.box, sample_rate_vec, omit_strata = "ZERO")
fixed_fmp.prox_index <- calculate_index2(fixed_fmp.prox_insp, cost_params, fixed_fmp.allo_lst, max_budget)
fixed_fmp.prox_rates <- prox_rates_from_budget2(fixed_fmp.prox_index, budget = 4.5e6)  
fixed_fmp.prox_rates[ADP == 2022]
attr(fixed_fmp.prox_rates, "costs")[ADP == 2022]

# To compare with old INDEX calculation of ISPN / CV_SCALING
# fixed_fmp.prox_index.old <- calculate_index3(fixed_fmp.prox_insp, cost_params, fixed_fmp.allo_lst, max_budget)
# fixed_fmp.prox_rates.old <- prox_rates_from_budget2(fixed_fmp.prox_index.old, budget = 4.5e6)  
# fixed_fmp.prox_rates[ADP == 2022]
# fixed_fmp.prox_rates.old[ADP == 2022]
# ggplot(fixed_fmp.prox_index$costs, aes(x = INDEX_COST, y = INDEX, color = as.factor(ADP))) + geom_line() 
# ggplot(fixed_fmp.prox_index.old$costs, aes(x = INDEX_COST, y = INDEX, color = as.factor(ADP))) + geom_line() 

#================#
# Save / Load ####
#================#

# Save all objects (excluding functions)
if(F) save(list = setdiff(ls(), lsf.str()), file = "results/draft_prelim_rates.rdata")
