# Rates for 2024 Draft ADP

# Author: Geoff Mayhew
# Start Date: 23 Aug 2024

#======================================================================================================================#
# Preparation ----------------------------------------------------------------------------------------------------------
#======================================================================================================================#

#===================#
## Load Packages ----
#===================#

library(data.table)         # Data wrangling
library(ggplot2)            # Plotting
library(grid)               # For unit.pmax  to get widths of grobs so that plots have matching dimensions
library(gridExtra)          # For arrangeGrob to combine plots
library(sf)                 # Spatial analyses
library(flextable)          # For print-ready tables
library(dplyr)              # For piping and handling sf objects

#=============================#
## Load data and data prep ----
#=============================#

# Fishing effort data from 2018 to 2022
# `spatiotemporal_boxes.rdata' is generated by /analyses/spatiotemporal_boxes/data_prep.R
#  load("analyses/allocation_evaluation/allocation_evaluation.Rdata")   # loads pc_effort_dt and trips_melt             # Older version prior to accounting for PCTC and new EM_TRW vessels
load("analyses/draft_rates/data_prep_outputs.Rdata")                                                                    # loads pc_effort_dt and trips_melt             
val_2018_2022_dt <- pc_effort_dt[ADP %in% 2018:2022]                                                                    

# Load the ADFG statistical area shapefile. '../' is needed for Rmarkdown to climb into parent folders.
stat_area_sf <- st_read(
  dsn = "source_data/ADFG_Stat_Area_shapefile/PVG_Statewide_2001_Present_GCS_WGS1984.shp", quiet = T) %>%
  select(STAT_AREA) %>%
  st_transform(crs = 3467)

# Load the Alaska map sf objects
load("source_data/ak_shp.rdata")      # shp_land, shp_nmfs, and shp_centroids added to global

#===============================#
## Prepare trips_melt object ----
#===============================#

# trips_melt has metrics and trip duration for all trips >= 2015. . 
# Add ADP year, STRATA, and DAYS of each TRIP_ID to trips_melt
trips_melt_add_data <- unique(pc_effort_dt[STRATA != "ZERO", .(ADP, TRIP_ID, STRATA, DAYS)])
trips_melt <- trips_melt_add_data[trips_melt, on = .(TRIP_ID)]
setcolorder(trips_melt, c("ADP", "STRATA", "TRIP_ID", "DAYS", "Metric", "Value"))
setkey(trips_melt, ADP, STRATA, TRIP_ID, DAYS, Metric, Value)
# Error-check
if(nrow(trips_melt[, .N, by = .(TRIP_ID)][N != uniqueN(trips_melt$Metric)])) stop("At least one trip has number of metrics != 3!")
# Remove records missing data
trips_melt <- trips_melt[!is.na(ADP)]

#===============#
## Functions ----
#===============#

source("analyses/allocation_evaluation/functions.R")

#=======================#
## Monitoring  Costs ----
#=======================#

# Derived from: https://docs.google.com/spreadsheets/d/1kcdLjq2Ck4XJBYP0EhrQpuknRgtQFt01LN3xUaCg7cI/edit?usp=sharing
# Monitoring cost models are applyed by ob_cost(), emfg_cost(), and emtrw_cost() functions
# Set all parameters involving monitoring costs
cost_params <- list(
  
  OB = list(
    day_rate_intercept          = 1870.4466666667,    # To calculate the sea day cost
    day_rate_slope              =   -0.2263733333,    # To calculate the sea day cost
    travel_day_rate             =  423.7867560407     # Expected cost of travel per day
  ),
  
  EMFG = list(
    emfg_v                      =  172,               # Size of fixed-gear EM vessel pool
    cost_per_vessel             = 5679.9002264045,
    cost_per_review_day         =  150.3237858616
  ),
  
  EMTRW = list(
    emtrw_goa_v                 =   39,               # Number of EM_TRW vessels that fish exclusively in the GOA. Current count is 39 for 2024.
    trip_to_plant_factor        =    3.8059361492,    # Used to predict plant days from trips
    amortized_equipment_per_VY  = 4100.7124800000,    # Per (Vessel x Year) amortized EM equipment install costs for GOA-only vessels
    equipment_upkeep_per_VY     = 4746.0398955882,    # Per (Vessel x Year) EM equipment maintenance cost for GOA-only vessels
    review_day_rate             =   27.9918948996,    # Per sea day cost for EM compliance review
    plant_day_rate              =  908.2225000000     # Per plant day cost for shoreside monitoring by observers
  )
)

#======================#
## Other Parameters ----
#======================#

sample_rate_vec <- seq(from = 0.0001, to = 0.9950, by = 0.0001) 

max_budget <- 7.00e6                        # This is used as a cutoff for allocation functions.
budget_lst <- list(3.5e6, 4.5e6, 5.25e6)    # List of budget scenarios to evaluate


#======================================================================================================================#
# Designs --------------------------------------------------------------------------------------------------------------
#======================================================================================================================#

#=============================#
## Stratification: Current ----
#=============================#

# Current box definitions
system.time(current.box <- define_boxes_3(
  val_2018_2022_dt, c(2e5, 2e5), time = c("week", 1, "TRIP_TARGET_DATE", "LANDING_DATE"),
  year_col = "ADP", stratum_cols = "STRATA", dmn_cols = c("BSAI_GOA", "GEAR"), geom = T))

# Apply current stratum definition and calculate mean trip durations
current.allo_lst <- update_strata(pc_effort_dt, trips_melt, stratum_cols = c("STRATA"), focus_years = 2018:2022)

# Estimate monitoring costs from method-specific cost models for a wide range of sample rates. This table will be used
# by all designs as it is design-agnostic. Takes 2-3 minutes to run.
system.time(cost_dt <- rates_to_costs_all(current.allo_lst, sample_rate_vec, cost_params, max_budget))
# FIXME : the ob_cost() model should be changed to logistic so that CPD doesn't decline infinitely with volume of days.
# For now, just exclude any instances where the OB_TOTAL decreases relative to the previous instance
cost_dt <- rbindlist(lapply(split(cost_dt, by = "ADP"), function(x) x[(which(x[-.N, OB_TOTAL] < x[-1, OB_TOTAL]))]))

#============================#
### Current x Equal Rates ####

current.equal <- rbindlist(lapply(budget_lst, function(x) cbind(BUDGET = x, allo_equal2(cost_dt, budget = x, current.allo_lst, cost_params))))

#===========================#
### Current x Status Quo ####

current.status_quo <- rbindlist(lapply(budget_lst, function(x) cbind(BUDGET = x, allo_status_quo(current.allo_lst, budget = x, cost_dt, cost_params))))

#====================#
### Current x CWB ####

current.cwb_prop <- calculate_cwb_Ph(current.box, sample_rate_vec)             # no changes needed here
current.cwb <- rbindlist(lapply(budget_lst, function(x) cbind(BUDGET = x, allo_cwb_loop2(current.cwb_prop, current.allo_lst, cost_params, budget = x, sqrt_cost = F)$rates)))

#=====================#
### Current x PROX ####

current.prox_insp <- calculate_interspersion(current.box, sample_rate_vec, omit_strata = "ZERO")
current.prox_index <- calculate_index2(current.prox_insp, cost_params, current.allo_lst, max_budget)
current.prox <- rbindlist(lapply(budget_lst, function(x) cbind(BUDGET = x, prox_rates_from_budget2(current.prox_index, budget = x))))

#=========================#
## Stratification: FMP ----
#=========================#

# Define boxes, splitting trips into strata based on FMP: BSAI and GOA
system.time(fmp.box <- define_boxes_3(
  val_2018_2022_dt, c(2e5, 2e5), time = c("week", 1, "TRIP_TARGET_DATE", "LANDING_DATE"),
  year_col = "ADP", stratum_cols = c("STRATA", "BSAI_GOA"), dmn_cols = c("GEAR"), geom = T ))
# Re-calculate trip durations
fmp.allo_lst <- update_strata(pc_effort_dt, trips_melt, stratum_cols = c("STRATA", "BSAI_GOA"), focus_years = 2018:2022)

#========================#
### FMP x Equal Rates ####

fmp.equal <- rbindlist(lapply(budget_lst, function(x) cbind(BUDGET = x, allo_equal2(cost_dt, budget = x, fmp.allo_lst, cost_params))))

#=======================#
### FMP x Status Quo ####

fmp.status_quo <- rbindlist(lapply(budget_lst, function(x) cbind(BUDGET = x, allo_status_quo(fmp.allo_lst, budget = x, cost_dt, cost_params))))

#================#
### FMP x CWB ####

fmp.cwb_prop <- calculate_cwb_Ph(fmp.box, sample_rate_vec)             # no changes needed here
fmp.cwb <- rbindlist(lapply(budget_lst, function(x) cbind(BUDGET = x, allo_cwb_loop2(fmp.cwb_prop, fmp.allo_lst, cost_params, budget = x, sqrt_cost = F)$rates)))

#=================#
### FMP x PROX ####

fmp.prox_insp <- calculate_interspersion(fmp.box, sample_rate_vec, omit_strata = "ZERO")
fmp.prox_index <- calculate_index2(fmp.prox_insp, cost_params, fmp.allo_lst, max_budget)
fmp.prox <- rbindlist(lapply(budget_lst, function(x) cbind(BUDGET = x, prox_rates_from_budget2(fmp.prox_index, budget = x))))


#=================================#
## Stratification: Fixed x FMP ----
#=================================#

# Redefine fixed-gear strata
fixed.pc_effort <- unique(copy(pc_effort_dt)[STRATA %like% "HAL|POT", STRATA := paste0(POOL, "_", "FIXED")])
fixed.val <- fixed.pc_effort[ADP %in% 2018:2022]
# Define boxes again split by FMP, but make neighboring gear-specific for the fixed-gear strata
system.time(fixed_fmp.box <- define_boxes_3(
  fixed.val, c(2e5, 2e5), time = c("week", 1, "TRIP_TARGET_DATE", "LANDING_DATE"),
  year_col = "ADP", stratum_cols = c("STRATA", "BSAI_GOA"), dmn_cols = c("GEAR"), geom = T ))
fixed_fmp.allo_lst <- update_strata(fixed.pc_effort, trips_melt, stratum_cols = c("STRATA", "BSAI_GOA"), focus_years = 2018:2022)

#==============================#
### FixedxFMP x Equal Rates ####

fixed_fmp.equal <- rbindlist(lapply(budget_lst, function(x) cbind(BUDGET = x, allo_equal2(cost_dt, budget = x, fixed_fmp.allo_lst, cost_params))))

#=============================#
### FixedxFMP x Status Quo ####

fixed_fmp.status_quo <- rbindlist(lapply(budget_lst, function(x) cbind(BUDGET = x, allo_status_quo(fixed_fmp.allo_lst, budget = x, cost_dt, cost_params))))

#======================#
### FixedxFMP x CWB ####

fixed_fmp.cwb_prop <- calculate_cwb_Ph(fixed_fmp.box, sample_rate_vec)             # no changes needed here
fixed_fmp.cwb <- rbindlist(lapply(budget_lst, function(x) cbind(BUDGET = x, allo_cwb_loop2(fixed_fmp.cwb_prop, fixed_fmp.allo_lst, cost_params, budget = x, sqrt_cost = F)$rates)))

#=======================#
### FixedxFMP x PROX ####

fixed_fmp.prox_insp <- calculate_interspersion(fixed_fmp.box, sample_rate_vec, omit_strata = "ZERO")
fixed_fmp.prox_index <- calculate_index2(fixed_fmp.prox_insp, cost_params, fixed_fmp.allo_lst, max_budget)
fixed_fmp.prox <- rbindlist(lapply(budget_lst, function(x) cbind(BUDGET = x, prox_rates_from_budget2(fixed_fmp.prox_index, budget = x))))


#================#
# Save / Load ####
#================#

# Save all objects (excluding functions)
if(F) save(list = setdiff(ls(), lsf.str()), file = "analyses/draft_rates/draft_rates.rdata")

#=======================================#
# Prepare all objects for evaluation ####
#=======================================#

if(F) load("analyses/draft_rates/draft_rates.rdata")

# Names of designs
# design_labels <- apply(
#   expand.grid(c("Equal Rates", "Status Quo", "Cost-weighte Boxes", "Proximity"), c("Current", "FMP", "Fixed-FMP")), 
#   1, function(x) paste(x[2], x[1], sep = " x "))

# Design abbreviations
design_abbrs <- apply(
  expand.grid(c("EQUAL", "STATUS_QUO", "CWB", "PROX"), c("CURRENT", "FMP", "FIXED_FMP")), 
  1, function(x) paste(x[2], x[1], sep = "."))

rates <- list(
    current.equal[, .(BUDGET, ADP, STRATUM_COL = STRATA, STRATA_N, SAMPLE_RATE = MON_RATE, n = round(MON_N))],
    current.status_quo[, .(BUDGET, ADP, STRATUM_COL = STRATA, STRATA_N, SAMPLE_RATE = MON_RATE, n = round(MON_N))],
    current.cwb[, .(BUDGET, ADP, STRATUM_COL, STRATA_N, SAMPLE_RATE = round(fh, 4), n = round(STRATA_N * fh))],
    current.prox[, .(BUDGET, ADP, STRATUM_COL, STRATA_N, SAMPLE_RATE, n = round(n))],
    
    fmp.equal[, .(BUDGET, ADP, STRATUM_COL = STRATA, STRATA_N, SAMPLE_RATE = MON_RATE, n = round(MON_N))],
    fmp.status_quo[, .(BUDGET, ADP, STRATUM_COL = STRATA, STRATA_N, SAMPLE_RATE = MON_RATE, n = round(MON_N))],
    fmp.cwb[, .(BUDGET, ADP, STRATUM_COL, STRATA_N, SAMPLE_RATE = round(fh, 4), n = round(STRATA_N * fh))],
    fmp.prox[, .(BUDGET, ADP, STRATUM_COL, STRATA_N, SAMPLE_RATE, n = round(n))],
    
    fixed_fmp.equal[, .(BUDGET, ADP, STRATUM_COL = STRATA, STRATA_N, SAMPLE_RATE = MON_RATE, n = round(MON_N))],
    fixed_fmp.status_quo[, .(BUDGET, ADP, STRATUM_COL = STRATA, STRATA_N, SAMPLE_RATE = MON_RATE, n = round(MON_N))],
    fixed_fmp.cwb[, .(BUDGET, ADP, STRATUM_COL, STRATA_N, SAMPLE_RATE = round(fh, 4), n = round(STRATA_N * fh))],
    fixed_fmp.prox[, .(BUDGET, ADP, STRATUM_COL, STRATA_N, SAMPLE_RATE, n = round(n))]
  )
names(rates) <- design_abbrs

# Prepare the effort objects #

# CURRENT
pc_effort.CURRENT <- copy(val_2018_2022_dt)
pc_effort.CURRENT[, STRATUM_COL := STRATA]

# FMP
pc_effort.FMP <- copy(val_2018_2022_dt)
pc_effort.FMP[, STRATUM_COL := paste0(STRATA, "-", BSAI_GOA)]

# FIXED_FMP
pc_effort.FIXED_FMP <- copy(fixed.val)
pc_effort.FIXED_FMP[, STRATUM_COL := paste0(STRATA, "-", BSAI_GOA)]

# Save rates and effort objects
if(F) save(rates, pc_effort.CURRENT, pc_effort.FMP, pc_effort.FIXED_FMP, file = "analyses/draft_rates/draft_rates_effort.rdata")

# Quick load
if(F) load("analyses/draft_rates/draft_rates_effort.rdata")

#=====================#
# Following PCFMAC ####
#=====================#

# Costs for FGEM used fully-loaded costs, some of which are 'amortized' costs (2018 annual report):
# .. categorizes one-time, amortized (for infrastructure, equipment, and capacity building, where the benefit extends 
# over several years and the cost is proportioned among each of those years), and recurring costs. Amortized costs are 
# largely the cost of installed EM equipment and assumes a 5-year life, recognizing that the actual equipment life may 
# be longer.
# [ ] We can't assume these start-up costs will totally restart in 5 years, but should be replaced with the costs of 
# replacing equipment, and need to again assume a lifetime for replacement systems.
# [ ] Have to subtract 'amortized' costs from each year and add in replacemtent costs
