# Rates for 2024 Draft ADP

# Author: Geoff Mayhew
# Start Date: 23 Aug 2024

#======================================================================================================================#
# Preparation ----------------------------------------------------------------------------------------------------------
#======================================================================================================================#

#===================#
## Load Packages ----
#===================#

library(data.table)         # Data wrangling
library(ggplot2)            # Plotting
library(grid)               # For unit.pmax  to get widths of grobs so that plots have matching dimensions
library(gridExtra)          # For arrangeGrob to combine plots
library(sf)                 # Spatial analyses
library(flextable)          # For print-ready tables
library(dplyr)              # For piping and handling sf objects

#=============================#
## Load data and data prep ----
#=============================#

# Fishing effort data from 2018 to 2022
# `spatiotemporal_boxes.rdata' is generated by /analyses/spatiotemporal_boxes/data_prep.R
#  load("analyses/allocation_evaluation/allocation_evaluation.Rdata")   # loads pc_effort_dt and trips_melt             # Older version prior to accounting for PCTC and new EM_TRW vessels
load("analyses/draft_rates/data_prep_outputs.Rdata")                                                                    # loads pc_effort_dt and trips_melt             
val_2018_2022_dt <- pc_effort_dt[ADP %in% 2018:2022]                                                                    

# Load the ADFG statistical area shapefile. '../' is needed for Rmarkdown to climb into parent folders.
stat_area_sf <- st_read(
  dsn = "source_data/ADFG_Stat_Area_shapefile/PVG_Statewide_2001_Present_GCS_WGS1984.shp", quiet = T) %>%
  select(STAT_AREA) %>%
  st_transform(crs = 3467)

# Load the Alaska map sf objects
load("source_data/ak_shp.rdata")      # shp_land, shp_nmfs, and shp_centroids added to global

#===============================#
## Prepare trips_melt object ----
#===============================#

# trips_melt has metrics and trip duration for all trips >= 2015. . 
# Add ADP year, STRATA, and DAYS of each TRIP_ID to trips_melt
trips_melt_add_data <- unique(pc_effort_dt[STRATA != "ZERO", .(ADP, TRIP_ID, STRATA, DAYS)])
trips_melt <- trips_melt_add_data[trips_melt, on = .(TRIP_ID)]
setcolorder(trips_melt, c("ADP", "STRATA", "TRIP_ID", "DAYS", "Metric", "Value"))
setkey(trips_melt, ADP, STRATA, TRIP_ID, DAYS, Metric, Value)
# Error-check
if(nrow(trips_melt[, .N, by = .(TRIP_ID)][N != uniqueN(trips_melt$Metric)])) stop("At least one trip has number of metrics != 3!")
# Remove records missing data
trips_melt <- trips_melt[!is.na(ADP)]

#===============#
## Functions ----
#===============#

source("analyses/allocation_evaluation/functions.R")

#=======================#
## Monitoring  Costs ----
#=======================#

# Derived from: https://docs.google.com/spreadsheets/d/1kcdLjq2Ck4XJBYP0EhrQpuknRgtQFt01LN3xUaCg7cI/edit?usp=sharing
# Monitoring cost models are applyed by ob_cost(), emfg_cost(), and emtrw_cost() functions
# Set all parameters involving monitoring costs
cost_params <- list(
  
  OB = list(
    day_rate_intercept          = 1870.4466666667,    # To calculate the sea day cost
    day_rate_slope              =   -0.2263733333,    # To calculate the sea day cost
    travel_day_rate             =  423.7867560407     # Expected cost of travel per day
  ),
  
  EMFG = list(
    emfg_v                      =  172,               # Size of fixed-gear EM vessel pool
    cost_per_vessel             = 5679.9002264045,
    cost_per_review_day         =  150.3237858616
  ),
  
  EMTRW = list(
    emtrw_goa_v                 =   39,               # Number of EM_TRW vessels that fish exclusively in the GOA. Current count is 39 for 2024.
    trip_to_plant_factor        =    3.8059361492,    # Used to predict plant days from trips
    amortized_equipment_per_VY  = 4100.7124800000,    # Per (Vessel x Year) amortized EM equipment install costs for GOA-only vessels
    equipment_upkeep_per_VY     = 4746.0398955882,    # Per (Vessel x Year) EM equipment maintenance cost for GOA-only vessels
    review_day_rate             =   27.9918948996,    # Per sea day cost for EM compliance review
    plant_day_rate              =  908.2225000000     # Per plant day cost for shoreside monitoring by observers
  )
)

#======================#
## Other Parameters ----
#======================#

sample_rate_vec <- seq(from = 0.0001, to = 0.9950, by = 0.0001) 
max_budget <- 7.00e6                        # This is used as a cutoff for allocation functions.
budget_lst <- list(4.8e6 + 1.019e6)    # List of budget scenarios to evaluate ($4.8M for PC contract, 1.019 for FGEM)


#======================================================================================================================#
# Designs --------------------------------------------------------------------------------------------------------------
#======================================================================================================================#

#=================================#
## Stratification: Fixed x FMP ----
#=================================#

# Redefine fixed-gear strata
fixed.pc_effort <- unique(copy(pc_effort_dt)[STRATA %like% "HAL|POT", STRATA := paste0(POOL, "_", "FIXED")])[STRATA != "EM_TRW"]
fixed.val <- fixed.pc_effort[ADP %in% 2018:2022]
# Define boxes again split by FMP, but make neighboring gear-specific for the fixed-gear strata
system.time(fixed_fmp.box <- define_boxes_3(
  fixed.val, c(2e5, 2e5), time = c("week", 1, "TRIP_TARGET_DATE", "LANDING_DATE"),
  year_col = "ADP", stratum_cols = c("STRATA", "BSAI_GOA"), dmn_cols = c("GEAR"), geom = T ))
fixed_fmp.allo_lst <- update_strata(fixed.pc_effort, trips_melt, stratum_cols = c("STRATA", "BSAI_GOA"), focus_years = 2018:2022)

#=======================#
### FixedxFMP x PROX ####

fixed_fmp.prox_insp <- calculate_interspersion(fixed_fmp.box, sample_rate_vec, omit_strata = "ZERO")
fixed_fmp.prox_index <- calculate_index2(fixed_fmp.prox_insp, cost_params, fixed_fmp.allo_lst, max_budget)
fixed_fmp.prox <- rbindlist(lapply(budget_lst, function(x) cbind(BUDGET = x, prox_rates_from_budget2(fixed_fmp.prox_index, budget = x))))

# Have $4.62 for OB and $1.2M for FG_EM. Estimated 2,275 observer days as well.
attr(prox_rates_from_budget2(fixed_fmp.prox_index, budget = budget_lst[[1]]), "costs")[ADP == 2022]
fixed_fmp.prox[ADP == 2022, .(STRATUM_COL, STRATA_N, SAMPLE_RATE = SAMPLE_RATE * 100, n)][order(-STRATUM_COL)]

#=====================================================#
### Create summary of rates for the 2024 Draft ADP ####

# Save draft adp rates for Council. 'draft_rates.rdata' and 'draft_rates_2.rdata' are not these rates, but the results
# of the analyses for the comparison of designs in the 2024 ADP. 'draft_rates_2024' will be the rates posted in the 
# executive summary of the 2024 Draft ADP.
rates_adp_2024_draft <- fixed_fmp.prox[ADP == 2022, .(STRATA = STRATUM_COL, SAMPLE_RATE)]

effort_summary <- unique(copy(pc_effort_dt)[
][ADP == 2022  
][STRATA %like% "HAL|POT", STRATA := paste0(POOL, "_", "FIXED")
][, .(ADP, POOL, STRATA, BSAI_GOA, TRIP_ID, DAYS)])[
][, STRATA := ifelse(STRATA == "ZERO", "ZERO", paste0(STRATA, "-", BSAI_GOA))]
effort_summary <- effort_summary[, .(N = uniqueN(TRIP_ID), D = sum(DAYS)), keyby = .(ADP, POOL, STRATA)]
# Convert ADP to draft ADP year
effort_summary[, ADP := 2024]
# Merge in sample rates
rates_adp_2024_draft <- rates_adp_2024_draft[effort_summary, on = .(STRATA)]
# Manually assign rates for strata outside the allocation process.
rates_adp_2024_draft[STRATA == "EM_TRW-GOA", SAMPLE_RATE := 0.3333]
rates_adp_2024_draft[STRATA == "ZERO", SAMPLE_RATE := 0]
setcolorder(rates_adp_2024_draft, c("ADP", "POOL", "STRATA", "N", "D", "SAMPLE_RATE"))

save(rates_adp_2024_draft, file = "analyses/draft_rates/rates_adp_2024_draft.rdata")
# Uploaded to google drive `Draft ADP Outputs` Folder: https://drive.google.com/file/d/1L5O6muYiAvbMg_WQkWy307dHYjYVvBBb/view?usp=drive_link

#=======================#
### FixedxFMP x CWB ####

fixed_fmp.cwb_prop <- calculate_cwb_Ph(fixed_fmp.box, sample_rate_vec)             # no changes needed here
fixed_fmp.cwb <- rbindlist(lapply(budget_lst, function(x) cbind(BUDGET = x, allo_cwb_loop2(fixed_fmp.cwb_prop, fixed_fmp.allo_lst, cost_params, budget = x, sqrt_cost = F)$rates)))
fixed_fmp.cwb[ADP == 2022, .(STRATUM_COL, STRATA_N, SAMPLE_RATE = fh * 100, nh)][order(-STRATUM_COL)]
