# This script 

#==================#
# Load Packages ####
#==================#

library(data.table)         # Data wrangling
library(ggplot2)            # Plotting
library(sf)                 # Spatial analyses
library(dplyr)              # Data wrangling sf objects

#===================#
# Load Functions ####
#===================#

source("analyses/spatiotemporal_boxes/functions.R")         

#==============#
# Load Data ####
#==============#

# Fishing effort data from 2018 to 2021
# `spatiotemporal_boxes.rdata' is generated by /analyses/spatiotemporal_boxes/data_prep.R
load("analyses/spatiotemporal_boxes/spatiotemporal_boxes.RData")

# Load the ADFG statistical area shapefile. '../' is needed for Rmarkdown to climb into parent folders.
stat_area_sf <- st_read(
  dsn = "source_data/ADFG_Stat_Area_shapefile/PVG_Statewide_2001_Present_GCS_WGS1984.shp", quiet = T) %>%
  select(STAT_AREA) %>%
  st_transform(crs = 3467)

# Simplify the dataset
effort <- unique(val_2018_2021_dt[
][STRATA != "ZERO" 
][, .(ADP, STRATA, ADFG_STAT_AREA_CODE, WEEK, GEAR, TRIP_ID)
][ADFG_STAT_AREA_CODE == 515832, ADFG_STAT_AREA_CODE := 515831        # 515832 is missing from shape file
][, TRIP_ID := .GRP, by = .(TRIP_ID)])

#=======================#
# Define post-strata ####
#=======================#

# Start with a 175km hex cells and radius = 1, with Week overlapping by +/- 1
dat <- define_poststrata(effort, space = c(2e5, 2e5*1), time = c("WEEK", 1), stratum_cols = c("ADP", "STRATA"))

# Combine post-stratum definitions with weights
ps_w_dt <- rbindlist(
  lapply(dat$W, as.data.table),
  idcol = "ADP.STRATA"
)[, c("ADP", "STRATA") := tstrsplit(ADP.STRATA, split = "[.]")
][, ADP := as.integer(ADP)
][, ADP.STRATA := NULL]
# Count trips in post-strata, combine with weights and STRATA N
# n = number of TRIP_IDs within or neighboring each post-stratum
ps_smry_dt <- dat$dt[, .(n = length(unique(TRIP_ID))), keyby=.(ADP, STRATA, PS_ID)]
ps_smry_dt[, N := dat$strata_N_dt[ps_smry_dt, N, on = .(ADP, STRATA)]]  # Merge in STRATA's N
ps_smry_dt[, W := ps_w_dt[ps_smry_dt, W, on = .(ADP, STRATA, PS_ID)]]   # Merge in each post-stratum's total weight

#======================#
# Set Sampling Rate ####
#======================#

# Sample rate to employ in comparison. Feel free to change this and see the results!
sample_rate <- 0.005

#==================#
# Deterministic ####
#==================#

# p = the probability that at least 1 trip within or neighboring the post-stratum is sampled
# n = number of trips within or neighboring the post-stratum (number of trips that can potentially be sampled and provide data to the PS)
# can calculate this as 1 - probability that all 'n' trips are not sampled
# Calculate the probability that the post-stratum will be near a sampled neighbor

deterministic <- copy(ps_smry_dt)[
][, p := 1 - ((1 - sample_rate)^n)                      # Calculate probability that at least 1 nearby trip is sampled in post-stratum
][, .(sum_W_p = sum(W * p)), by = .(ADP, STRATA, N)][   # Multiply the probability by the weight (number of component trips centered in the box)
][, MEAN_PROP_N_IN_SAMPLED_PS := sum_W_p / N][]         # Calculate the average total number of trips in sampled boxes.

#===============#
# Stochastic ####
#===============#

# Randomly sample trips, see which post-strata are sampled or are near sampled neighbors
sample_iter_vec <- 1:1000L            # 1K to 10K is reasonably fast enough
trip_ids <- unique(dat$dt$TRIP_ID)
stochastic <- rbindlist(lapply(sample_iter_vec, function(x) {
  # Sample trip_ids according to 'sample_rate'
  sampled_trip_ids <- data.table(TRIP_ID = trip_ids[runif(n = length(trip_ids)) < sample_rate])
  # Find which ADP x STRATA x PS_ID include the sampled trip_ids 
  sampled_ps_ids <- unique(dat$dt[sampled_trip_ids, on = .(TRIP_ID), .(ADP, STRATA, PS_ID)])
  ps_smry_dt[sampled_ps_ids, on = .(ADP, STRATA, PS_ID)][
  ][, .(sum_W = sum(W)), by = .(ADP, STRATA, N)
  ][, .(MEAN_PROP_N_IN_SAMPLED_PS = sum_W/N), by = .(ADP, STRATA)]
}), idcol  = "ITER")
# Average across all iterations.
stochastic_mean <- stochastic[, .(
  MEAN_PROP_N_IN_SAMPLED_PS = sum(MEAN_PROP_N_IN_SAMPLED_PS) / max(sample_iter_vec)), 
  by = .(ADP, STRATA)]
 
#============#
# Compare ####
#============#

ggplot(deterministic, aes(x = as.factor(ADP), y = MEAN_PROP_N_IN_SAMPLED_PS)) + 
  geom_col() + facet_wrap(~STRATA) + 
  labs(x = "Year", y = "Proportion of trips in sampled boxes", subtitle = "Columns = deterministic, Violins = stochastic") + 
  geom_violin(data = stochastic, draw_quantiles = 0.5, color = "blue", alpha = 0.5) + 
  geom_point(data = stochastic_mean, color = "dodgerblue", shape = 4, stroke = 1)
