# analyses/allocation_evaluation/stratification_exploration.R 

# Investigation of how many trips would be in hypothetical strata, considering changes to gear type (status quo, putting
# mixed-gear trips into distinct strata, or pooling all fixed-gear trips into one strata) crossed with further
# sttratifying by FMP (status quo, BSAI vs GOA, or BS vs AI vs GOA). To assess whether certain stratifications make 
# sense, the probability that each stratum X FMP is reasonbly sized, we consider the probability that each cell would
# be sampled and the probablity that two or fewer samples would be collected, given a 15% sample rate.

# The resulting preadsheet outputs are in our google drive:
# https://docs.google.com/spreadsheets/d/18YKPncs3P2pbafssWQ-crvV2KAhn16Yx/edit?usp=sharing&ouid=112928343270640187258&rtpof=true&sd=true

#======================================================================================================================#
# Preparation ----------------------------------------------------------------------------------------------------------
#======================================================================================================================#

#===================#
## Load Packages ----
#===================#

library(data.table)         # Data wrangling
library(ggplot2)            # Plotting
library(sf)                 # Spatial analyses
library(flextable)          # For print-ready tables
library(dplyr)              # For piping and handling sf objects


#=============================#
## Load data and data prep ----
#=============================#

# Fishing effort data from 2018 to 2022
# `spatiotemporal_boxes.rdata' is generated by /analyses/spatiotemporal_boxes/data_prep.R
load("analyses/allocation_evaluation/allocation_evaluation.Rdata")   # loads pc_effort_dt
val_2018_2022_dt <- pc_effort_dt[ADP %in% 2018:2022]
# Subset relevant columns
base <- unique(val_2018_2022_dt[, .(ADP, POOL, STRATA, AGENCY_GEAR_CODE, BS_AI_GOA, BSAI_GOA, TRIP_ID)])


#===============#
## Functions ----
#===============#

# This loop applies formatting to flextables to merge grouped cells manually
merge_loop <- function(tbl, merge_lst, j) {
  # tbl <- copy(tbl1); merge_lst <- copy(merge_group_1); j <- 2:4
  for(j1 in j) {
    for(i1 in 1:length(merge_lst)) {
      tbl <- tbl %>% merge_at(i = merge_lst[[i1]], j = j1)
    }
  }
  tbl %>% fix_border_issues() %>% theme_box()
}

# The function combines and formats the counts from the different FMP stratification. Outputs in both dt and list form.
trip_count_table <- function(BSAIGOA, BSAI_GOA, BS_AI_GOA, year) {
  
  # Combine into one table
  temp <- BS_AI_GOA[ADP == year]
  temp[, BSAI_GOA := ifelse(BS_AI_GOA %in% c("BS", "AI"), "BSAI", "GOA")]  # Make a helper object that can join on BSAI
  smry <- BSAIGOA[ADP == year][
  ][BSAI_GOA[ADP == year], on = .(ADP, POOL, STRATA)
  ][temp, on = .(ADP, POOL, STRATA, BSAI_GOA)]
  
  # Identify cell rows to merge together
  merge_group_1 <- as.matrix(smry[, .(.I, .GRP), by = .(STRATA, N)][, .(I, GRP)])
  merge_group_1 <- split(merge_group_1[, 1], f = merge_group_1[, 2])
  merge_group_2 <- as.matrix(smry[, .(.I, .GRP), by = .(STRATA, BSAI_GOA, N_BSAI_GOA)][, .(I, GRP)])
  merge_group_2 <- split(merge_group_2[, 1], f = merge_group_2[, 2])
  
  setnames(smry, c("BSAI_GOA", "N_BSAI_GOA", "BS_AI_GOA", "N_BS_AI_GOA"), c("FMP1", "N1", "FMP2", "N2"))
  
  # Create the table
  tbl <- smry[, -"ADP"] %>% flextable() %>% merge_v(j = 1) %>% theme_box()
  tbl <- merge_loop(tbl, merge_group_1, j = 2:3)
  tbl <- merge_loop(tbl, merge_group_2, j = 4:5)
  tbl <- tbl %>% 
    # rotate(rotation = 'btlr', part = "header", i = 1, j = c(4:7)) %>% 
    align(i = 1, align = "center", part = "header") %>% autofit() %>%
    add_header_row(values = c("", "FMP Status quo", "BSAI vs GOA", "BS vs AI vs GOA"), colwidths = c(1, 2, 2, 2)) %>%
    fontsize(size = 8, part = "body") %>%
    padding(padding.top = 1, padding.bottom = 1)
  
  # Calculate probability of getting 0 and <3 trips into each FMP grouping
  prob <- copy(smry)[
  ][, P_FMP0_0 := round(pbinom(0, size = N, prob = 0.15), 5)   # Prob of 0
  ][, P_FMP0_3 := round(pbinom(2, size = N, prob = 0.15), 5)   # Prob of <3
  ][, P_FMP1_0 := round(phyper(q = 0, m = N1, n = N-N1, k = round(N*0.15)), 5)    # Prob of 0
  ][, P_FMP1_3 := round(phyper(q = 2, m = N1, n = N-N1, k = round(N*0.15)), 5)    # Prob of <3
  ][, P_FMP2_0 := round(phyper(q = 0, m = N2, n = N-N2, k = round(N*0.15)), 5)    # Prob of 0
  ][, P_FMP2_3 := round(phyper(q = 2, m = N2, n = N-N2, k = round(N*0.15)), 5)][] # Prob of <3
  setcolorder(prob, c("ADP", "POOL", "STRATA", "N", "P_FMP0_0", "P_FMP0_3", "FMP1", "N1", "P_FMP1_0", "P_FMP1_3", "FMP2", "N2", "P_FMP2_0", "P_FMP2_3"))
  # Copy-paste this table to excel and apply conditional formatting
  
  list(dt = prob, tbl = tbl)
}


#======================================================================================================================#
# Split current strata by FMP ------------------------------------------------------------------------------------------
#======================================================================================================================#

sq <- copy(base)
sq <- sq[, .(N = uniqueN(TRIP_ID)), keyby = .(ADP, POOL, STRATA)]
dcast(sq, POOL + STRATA ~ ADP, value.var = "N", fill = 0)

# Further Split by BSAI_GOA
sq_bsai_goa <- base[, .(N_BSAI_GOA = uniqueN(TRIP_ID)), keyby = .(ADP, POOL, STRATA, BSAI_GOA)]
dcast(sq_bsai_goa, POOL + STRATA + BSAI_GOA ~ ADP, value.var = "N_BSAI_GOA", fill = 0)
dcast(sq_bsai_goa[ADP == 2022], POOL + STRATA ~ BSAI_GOA, value.var = "N_BSAI_GOA", fill = 0)

# Further split by BS_AI_GOA
sq_bs_ai_goa <- base[, .(N_BS_AI_GOA = uniqueN(TRIP_ID)), keyby = .(ADP, POOL, STRATA, BS_AI_GOA)]
dcast(sq_bs_ai_goa, POOL + STRATA + BS_AI_GOA ~ ADP, value.var = "N_BS_AI_GOA", fill = 0)
dcast(sq_bs_ai_goa[ADP == 2022], POOL + STRATA ~ BS_AI_GOA, value.var = "N_BS_AI_GOA", fill = 0)

# Create the tables
sq_res <- trip_count_table(sq, sq_bsai_goa, sq_bs_ai_goa, 2022)
sq_res$dt
sq_res$tbl


#======================================================================================================================#
# Create new mixed-gear Strata -----------------------------------------------------------------------------------------
#======================================================================================================================#
# Separate HAL, POT and FG_MIXED as well as PTR, NPT, and TRW_MIXED

mixed <- copy(base)[AGENCY_GEAR_CODE != "JIG"]
mixed[, STRATA := ifelse(any(AGENCY_GEAR_CODE == "HAL") & any(AGENCY_GEAR_CODE == "POT"), paste0(POOL, "_FG_MIXED") , STRATA),  by= .(TRIP_ID)]
mixed[, STRATA := ifelse(any(AGENCY_GEAR_CODE == "NPT") & any(AGENCY_GEAR_CODE == "PTR"), paste0(POOL, "_TRW_MIXED") , STRATA),  by= .(TRIP_ID)]
mixed[, STRATA := ifelse(all(AGENCY_GEAR_CODE == "HAL"), paste0(POOL, "_FG_HAL"), STRATA), by= .(TRIP_ID)]
mixed[, STRATA := ifelse(all(AGENCY_GEAR_CODE == "POT"), paste0(POOL, "_FG_POT"), STRATA), by= .(TRIP_ID)]
mixed[, STRATA := ifelse(all(AGENCY_GEAR_CODE == "PTR"), paste0(POOL, "_TRW_PTR"), STRATA), by= .(TRIP_ID)]
mixed[, STRATA := ifelse(all(AGENCY_GEAR_CODE == "NPT"), paste0(POOL, "_TRW_NPT"), STRATA), by= .(TRIP_ID)]
mixed_sq <- mixed[, .(N = uniqueN(TRIP_ID)), keyby = .(ADP, POOL, STRATA)]
dcast(mixed_sq, POOL + STRATA ~ ADP, value.var = "N", fill = 0)

# Further Split by BSAI_GOA
mixed_bsai_goa <- mixed[, .(N_BSAI_GOA = uniqueN(TRIP_ID)), keyby = .(ADP, POOL, STRATA, BSAI_GOA)]
dcast(mixed_bsai_goa, POOL + STRATA + BSAI_GOA ~ ADP, value.var = "N_BSAI_GOA", fill = 0)
dcast(mixed_bsai_goa[ADP == 2022], POOL + STRATA ~ BSAI_GOA, value.var = "N_BSAI_GOA", fill = 0)

# Further split by BS_AI_GOA
mixed_bs_ai_goa <- mixed[, .(N_BS_AI_GOA = uniqueN(TRIP_ID)), keyby = .(ADP, POOL, STRATA, BS_AI_GOA)]
dcast(mixed_bs_ai_goa, POOL + STRATA + BS_AI_GOA ~ ADP, value.var = "N_BS_AI_GOA", fill = 0)
dcast(mixed_bs_ai_goa[ADP == 2022], POOL + STRATA ~ BS_AI_GOA, value.var = "N_BS_AI_GOA", fill = 0)

# Create the tables
mixed_res <- trip_count_table(mixed_sq, mixed_bsai_goa, mixed_bs_ai_goa, 2022)
mixed_res$dt
mixed_res$tbl


#======================================================================================================================#
# Pool HAL and POT into FG strata --------------------------------------------------------------------------------------
#======================================================================================================================#

# Pool HAL+POT fixed-gear strata
fg <- copy(base)
fg[, STRATA := ifelse(STRATA %like% "HAL|POT", paste0(POOL, "_", "FIXED"), STRATA)]
fg <- fg[, .(N = uniqueN(TRIP_ID)), keyby = .(ADP, POOL, STRATA)]
dcast(fg, POOL + STRATA ~ ADP, value.var = "N", fill = 0)

# Further Split by BSAI_GOA
fg_bsai_goa <- copy(base)
fg_bsai_goa[, STRATA := ifelse(STRATA %like% "HAL|POT", paste0(POOL, "_", "FIXED"), STRATA)]
fg_bsai_goa <- fg_bsai_goa[, .(N_BSAI_GOA = uniqueN(TRIP_ID)), keyby = .(ADP, POOL, STRATA, BSAI_GOA)]
dcast(fg_bsai_goa, POOL + STRATA + BSAI_GOA ~ ADP, value.var = "N_BSAI_GOA", fill = 0)
dcast(fg_bsai_goa[ADP == 2022], POOL + STRATA ~ BSAI_GOA, value.var = "N_BSAI_GOA", fill = 0)

# Further split by BS_AI_GOA
fg_bs_ai_goa <- copy(base)
fg_bs_ai_goa[, STRATA := ifelse(STRATA %like% "HAL|POT", paste0(POOL, "_", "FIXED"), STRATA)]
fg_bs_ai_goa <- fg_bs_ai_goa[, .(N_BS_AI_GOA = uniqueN(TRIP_ID)), keyby = .(ADP, POOL, STRATA, BS_AI_GOA)]
dcast(fg_bs_ai_goa, POOL + STRATA + BS_AI_GOA ~ ADP, value.var = "N_BS_AI_GOA", fill = 0)
dcast(fg_bs_ai_goa[ADP == 2022], POOL + STRATA ~ BS_AI_GOA, value.var = "N_BS_AI_GOA", fill = 0)

# Create the tables
fg_res <- trip_count_table(fg, mixed_bsai_goa, mixed_bs_ai_goa, 2022)
fg_res$dt
fg_res$tbl